### ISSUE TITLE
Out of range float values are not JSON compliant

### ISSUE THREAD

**Issue by tamkaho** [bluenote10/tabloo#8]
When I click on plot I get the following error message:

Any idea why is that? There are some nans / string values in the dataframe but the columns I selected should all be numeric.

``
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/tabloo/server.py", line 98, in get_data
    filter, sort_column, sort_kind, page, pagination_size))
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/tabloo/server.py", line 66, in json_response
    response = make_response(to_json(data))
  File "/home/username/anaconda3/envs/hist/lib/python3.7/site-packages/tabloo/backend.py", line 33, in to_json
    return json.dumps(data, default=converter, allow_nan=False)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/username/anaconda3/envs/hist/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
``

**Comment by bluenote10** [comment]
Yes, I was running into that myself already. Background: Python's standard `json` implementation is unfortunately not conforming to the JSON standard :(. Tabloo contains a few work-arounds for that, but up until a few commits ago they might not have been working that well (and there might still be cases that aren't fully covered).

I have just released a new version (0.0.13) which contains these latest improvements. Could you try with the updated version? 

If you still have the problem with the new version it would be really helpful if you could extract a minimal reproducing example (a small fraction of the data frame) for further investigation.

**Comment by bluenote10** [comment]
I hope this has resolved your issue -- otherwise just let me know.
